// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ssl} from '../models';

export function AnalyzeDomain(arg1:string):Promise<ssl.SSLResult>;
